# Generated by Django 2.2.13 on 2020-07-22 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('nickname', models.CharField(max_length=120, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('arrival_date', models.DateField(verbose_name='Дата прибытия')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('growth', models.FloatField(verbose_name='Рост')),
                ('special_signs', models.CharField(max_length=300, verbose_name='Особые приметы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Список животных',
            },
        ),
    ]
