# Generated by Django 2.2.13 on 2020-07-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
